namespace:
    - Pinet\EPG\
route_rules:
    - /application/rules/route.rules
    - /rules/route.rules
filters:
    - Widget
    - Rules
    - Form
    - Scss
    - Css
    - SmartyView
    - MustacheView
    - JsonView
    - DirectView
helpers:
    - web
    - html
babel: /opt/local/bin/node /opt/local/bin/babel
default_view: Smarty
widget_cache: true
#debug_sass: true
resolutions:
    - 320
    - 360
    - 375
    - 414
    - 480
    - 640
    - 769
    - 1280
    - 1440
    - 1920
    - 2880
mss_url: http://localhost/~jack/huazhu/mss/index.php
file_dist: /tmp/dist # The distination for all the local file storage
sling: # The configuration for accessing mms server
    host: localhost
    port: 8080
    username: admin
    password: admin
sass_preload:
    - variables
datasources:
    mysql:
        table_prefix: ''
        type: MySQLi
        database: mam
columns:
    movie: 电影
    drama: 电视剧
    show: 综艺
    anime: 动漫
    education: 教育
    sports: 体育
    newsreel: 纪录片
    macrofilm: 微电影
image_url_base:
    - http://localhost/~jack/huazhu/mss/index.php/api/show/
logger:
    handlers:
        Stream:
            - php://stdin
            - debug
        FirePHP:
            - debug
        ChromePHP:
            - debug
    processors:
        - Git
        - PsrLogMessage
        - Introspection
        - Tag
